# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.1.0/variables.json
# == Variables ==
#
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  mailstoreConnector:
    localhostImap:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: imap
      # Host for store connection
      host: localhost
      # Port for store connection (only needed if not default)
      port: "-1"
      # User name for store connection
      user: debug@localdomain.test
      # Password for store connection
      #[password]
      password: ${decrypt:}
      # show debug output for connection
      debug: true
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
        mail:
          smtp:
            ssl:
              enable: true
            starttls:
              enable: true
          imap:
            ssl:
              enable: true
              required: true
            auth: false
          imaps:
            ssl:
              checkserveridentity: true
              trust: "*"
      # only set below credential when you go with oauth2
      # mail.imaps.auth.mechanisms: 'XOAUTH2'
      # mail.imaps.sasl.enable: 'true'
      # mail.imaps.sasl.mechanisms: 'XOAUTH2'

      # com.axonivy.connector.oauth.BasicUserPasswordProvider for Basic Authentication
      # com.axonivy.connector.oauth.AzureOauth2UserPasswordProvider for AzureOauth2UserPasswordProvider
      userPasswordProvider: ""
      # only set below credential when you go with oauth2
      # tenant to use for OAUTH2 request.
      # set the Azure Directory (tenant) ID, for application requests.
      tenantId: ""
      # Your Azure Application (client) ID, used for OAuth2 authentication
      appId: ""
      # Secret key from your applications "certificates & secrets" (client secret)
      secretKey: ""
      # for client_credentials: https://outlook.office365.com/.default
      scope: ""
      grantType: ""
    localhostImapBasicAuthentication:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: imap
      # Host for store connection
      host: localhost
      # Port for store connection (only needed if not default)
      port: "-1"
      # User name for store connection
      user: debug@localdomain.test
      # Password for store connection
      #[password]
      password: ${decrypt:}
      # show debug output for connection
      debug: true
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
        mail:
          smtp:
            ssl:
              enable: "true"
            starttls:
              enable: "true"
          imap:
            starttls:
              enable: "true"
              required: "true"
          imaps:
            ssl:
              checkserveridentity: "true"
              #trust: "*"
      userPasswordProvider: com.axonivy.connector.oauth.BasicUserPasswordProvider
    localhostImapAzureOauth2Authentication:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: imap
      # Host for store connection
      host: localhost
      # Port for store connection (only needed if not default)
      port: "-1"
      # User name for store connection
      user: debug@localdomain.test
      # Password for store connection
      #[password]
      password: ${decrypt:}
      # show debug output for connection
      debug: "true"
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
        mail:
          imaps:
            ssl:
              checkserveridentity: "false"
              trust: "*"
            auth:
              # only set below credential when you go with oauth2
              mechanisms: XOAUTH2
            sasl:
              enable: "true"
              mechanisms: XOAUTH2
      userPasswordProvider: com.axonivy.connector.oauth.AzureOauth2UserPasswordProvider
      # only set below credential when you go with oauth2
      # tenant to use for OAUTH2 request.
      # set the Azure Directory (tenant) ID, for application requests.
      tenantId: ""
      # Your Azure Application (client) ID, used for OAuth2 authentication
      appId: ""
      # Secret key from your applications "certificates & secrets" (client secret)
      secretKey: ""
      # for client_credentials/password: https://outlook.office365.com/.default
      scope: ""
      grantType: ""
  # login microsoft azure
  azureOAuth:
    loginUrl: login.microsoftonline.com
